// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ-jGMMX5WfwFJ2ShGJ0bPD1c_rGAzJS4',
    appId: '1:872796251085:web:7534bf2b999d8457991a84',
    messagingSenderId: '872796251085',
    projectId: 'temukerja-8d811',
    authDomain: 'temukerja-8d811.firebaseapp.com',
    storageBucket: 'temukerja-8d811.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9gFIn2ny0-RmK5fLPlSc8-pbqA8UpYY8',
    appId: '1:872796251085:android:e773b499a9b7e344991a84',
    messagingSenderId: '872796251085',
    projectId: 'temukerja-8d811',
    storageBucket: 'temukerja-8d811.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5f-qoF7UjcI8oFACIGHxXWxvtiLkhbbA',
    appId: '1:872796251085:ios:67ed38e27f3b8a31991a84',
    messagingSenderId: '872796251085',
    projectId: 'temukerja-8d811',
    storageBucket: 'temukerja-8d811.appspot.com',
    iosBundleId: 'com.example.temukerjaApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5f-qoF7UjcI8oFACIGHxXWxvtiLkhbbA',
    appId: '1:872796251085:ios:67ed38e27f3b8a31991a84',
    messagingSenderId: '872796251085',
    projectId: 'temukerja-8d811',
    storageBucket: 'temukerja-8d811.appspot.com',
    iosBundleId: 'com.example.temukerjaApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ-jGMMX5WfwFJ2ShGJ0bPD1c_rGAzJS4',
    appId: '1:872796251085:web:9194a1aa4daa60bb991a84',
    messagingSenderId: '872796251085',
    projectId: 'temukerja-8d811',
    authDomain: 'temukerja-8d811.firebaseapp.com',
    storageBucket: 'temukerja-8d811.appspot.com',
  );
}
